Repository mad-af/ofa, pull requests merged in 2022-10, with the labels that each got.

#1 Add Middleware
  README.md
  bin/middleware/basic_auth.go
  bin/modules/utilities/zone/hendlers/http_handler.go
  bin/modules/utilities/zone/usecases/usecase.go
  bin/modules/utilities/zone/usecases/usecase_interface.go
  bin/pkg/response/error.go
  bin/pkg/utils/validate.go
  go.mod
Labels: enhancement

#2 add repositories and installation gorm
  bin/modules/utilities/zone/hendlers/http_handler.go
  bin/modules/utilities/zone/repositories/gorm.go
  bin/modules/utilities/zone/repositories/repository_interface.go
  bin/modules/utilities/zone/usecases/usecase.go
  bin/modules/utilities/zone/usecases/usecase_interface.go
  bin/repositories/gorm.go
  go.mod
Labels: enhancement, hacktoberfest-accepted

#3 update api list zone
  bin/modules/utilities/zone/helpers/constant.go
  bin/modules/utilities/zone/models/model.go
  bin/modules/utilities/zone/repositories/gorm.go
  bin/modules/utilities/zone/repositories/repository_interface.go
  bin/modules/utilities/zone/usecases/usecase.go
Labels: enhancement, hacktoberfest-accepted

#6 Develop
  bin/app/server.go
  bin/repositories/gorm.go
  bin/repositories/math.go
Labels: hacktoberfest-accepted

#7 divide
  bin/app/server.go
  bin/repositories/math.go
Labels: hacktoberfest-accepted

#8 multiplication
  bin/app/server.go
  bin/repositories/math.go
Labels: hacktoberfest-accepted

#9 Develop
  bin/app/server.go
  bin/repositories/math.go
Labels: hacktoberfest-accepted
